version: '3.8'
services:
  server:
    container_name: api-container
    restart: always
    build: ./server
    ports: 
      - "5000:5000"
    volumes:
      - './server:/app'
    depends_on: 
      - mysql
  client:
    container_name: client-container
    restart: always
    build: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports: 
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  mysql:
    container_name: mysql-container
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - docto-db:/var/lib/mysql
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASS=${DB_PASSWORD}
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
      # Make it small
      - GZIP_LEVEL=9
    restart: unless-stopped
# Names our volume
volumes:
  docto-db:

